### ISSUE TITLE
[BUG] Crashes on Fabric 1.17.1-0.12.1

### ISSUE THREAD

**Issue by lukebemish** [UltraBlackLinux/MineMenuFabric#27]
## Expected Behavior
Should run without crashing

## Actual Behavior
Crashes almost immediately on launch.

logs: https://pastebin.com/raw/PzYiwU8A

Not everything is logged. Everything not logged is copied from the console below:

```
Exception in thread "main" java.lang.RuntimeException: Minecraft has crashed
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:571)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.IllegalArgumentException
	at com.google.gson.internal.$Gson$Preconditions.checkArgument($Gson$Preconditions.java:46)
	at com.google.gson.GsonBuilder.registerTypeAdapter(GsonBuilder.java:497)
	at net.minecraft.client.main.Main.main(Main.java:120)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
	... 2 more
```

## Steps to Reproduce the Problem

1. Install the newest versions of fabric-api, cloth-config, cloth-api, and MineMenuFabric-6.0-1.17
2. Launch; observe crash

**Comment by UltraBlackLinux** [comment]
your config might be messed up - or the mod isn't compatible w/  1.17.1

tbh I quit developing this mod. 
Java sucks and I don't have the time anymore.
